### PR TITLE
Fix pattern

### PR DESCRIPTION
**Pull request by ThomasBarnekow**
This pull request demonstrates how the pattern I proposed in the discussion we had in my repo should be implemented.

A few things of note:

- You added some of the "extended" methods (e.g., `where()`, `skip()`, `select()`) to `LinqBase`. If the idea is still to have a minimal class that only provides the bare minimum, those methods should be added to `LinqExtendedBase`.
- Overall, the set of filter methods is a bit confusing and creates breaking changes (which should be reflected by bumping the major version). The question is whether we could have multiple overloads of just a `filter()` method:
  - You renamed the `filters()` methods to `applyFilters()`. While I like the new name better, this is a breaking change.
  - You renamed the `filter(...filters: IterableFilter<T>[])` method to `filterWith(...filters: IterableFilter<T>[])`. This is also a breaking change. I don't see why you needed to do this.
  - The remaining `filter(filter: IterableFilter<T>): TLinq` only takes a single parameter.
- I removed a "filter" method that is actually a transformation (as you already stated in the documentation): `filter<TResult>(filter: IterableValueTransform<T, TResult>): Linq<TResult>`. This broke some unit tests, which I fixed by using `transform(notNull)` instead of `filter(notNull)`. In my mind, a filter should only ever return sequences of the exact same type. However, `notNull` is a transformation (that even sits in your transformations subfolder) and should, therefore, be used as a parameter of the `transform()` function rather than a `filter()` function. I believe that removing that method solved one of your problems because all `filter()` overloads can now have a return type of `TLinq`.
- You added methods to `Linq<T>` and `LinqExtended<T>`, which is not necessary with the proposed pattern. The idea of this pattern is to only create a concrete subclass with no additional methods as I demonstrate in this pull request (and previously in my repo). Further, the idea is to have an inheritance hierarchy like `LinqBase`<= `LinqExtendedBase` <= `LinqEvenMoreExtendedBase`, where this repo provides `LinqBase` and `LinqExtendedBase` and users could optionally add further abstract (e.g., `LinqEvenMoreExtendedBase`) or concrete subclasses. Subclasses "tap" into that hierarchy by extending from `LinqBase`, `LinqExtendedBase`, or `LinqEvenMoreExtendedBase`, not from `Linq` or `LinqExtended`. 
- Where methods implemented by `LinqBase` or `LinqExtendedBase` return a `Linq<T>` or `LinqExtended<T>`, those methods would have to be overridden by more derived classes wanting to return themselves or subclasses of themselves. The question I asked in our discussion was whether you'd have an idea on how this could be avoided. My attempts at using generic factory methods were not successful. Should this in fact be impossible to realize, overriding such methods in subclasses as currently done is the only option.
- I changed the implementations of `first()`, `last()`, and `single()` and the corresponding `xOrDefault()` methods. Firstly, they should all take an optional predicate. Secondly, `xOrDefault()` should not take a default value if you want to mimic the .NET counterparts. Thus, my proposed implementations take a predicate but no default value. However, I added the `defaultIfEmpty(defaultValue: T): TLinq` method to deal with that.

This PR is not yet complete and we should discuss the shape of the API.

Lastly, I apologize for any unnecessary formatting changes that are introduced by Prettier. There is no .prettierrc, so we did not use the same settings.

### CODE REVIEW

**Comment by electricessence** [comment]
Sorry, I commented in more detail on our other thread.  Please close that one if you think it's ok.
This comment is important:
https://github.com/OpenXmlDev/linq-to-xml/issues/1#issuecomment-1025156225

**Comment by electricessence** [comment]
First off, as much as I would have liked to remove the filter method that acts as a transform, I cannot because it is a legitimate breaking change that is not an uncommon use case.

For example:
```ts
linqSequence.filter(notNull);
```
A very common case in the tests.  `notNull` is actually a transform but from a consumers perspective, it is a filter.  The type safety considers the result to be `T` _but not the same_ (`NotNull<T>`) so it isn't a pure transform.  The code that drives the method is not any different, it's simply a type safety problem.

**Comment by electricessence** [comment]
> You added methods to Linq<T> and LinqExtended<T>, which is not necessary with the proposed pattern.

Consider that one of the more common use cases for LINQ is iterating filtered results.  `Linq<T>` can still cover most of these use cases without incurring more download overhead.  I took into consideration the balance of the feature set for what default functionality it exposes.  For example, with the new `LinqBase<T>` pattern, the `.where` method (a very common use case) could remain available for all inherited classes.  The benefit simply outweighed the cost especially when this repo is designed with granularity in mind.  If someone wanted a lighter weight version of `Linq<T>` or even less from `LinqBase<T>` they could easily just use the filters, transforms, and resolutions by themselves (functionally) without a class and incur no additional overhead.

**Comment by electricessence** [comment]
> I changed the implementations of first(), last(), and single() and the corresponding xOrDefault() methods. Firstly, they should all take an optional predicate. Secondly, xOrDefault() should not take a default value if you want to mimic the .NET counterparts. Thus, my proposed implementations take a predicate but no default value. However, I added the defaultIfEmpty(defaultValue: T): TLinq method to deal with that.

I have a hard time agreeing with this one as I've previously spent a lot of time considering why it should or shouldn't be that way.
```ts
linqSequence
  .where(predicate)
  .firstOrDefault()
// vs
linqSequence
  .firstOrDefault(predicate)
```
Here's the problem:  You simply can't have the best of both worlds here.
Exposing a default value option is important in TypeScript because there might be a preference of returning `null` instead of `undefined` or `0` instead of `undefined` if it's a number.  Covering default value use cases would be a painful and probably bug ridden block of code.  This is not an issue in C# as it has a real type system that will return 0 as a default value for a number and null for a string, etc.  IMO, the former `.where(predicate).firstOrDefault()` is a more explicit, and simpler implementation. 

As a side effect of this type of implementation, it can be difficult if not impossible to have a delegate as a parameter as it could be confused with an element in the collection.

**Comment by electricessence** [comment]
> Where methods implemented by LinqBase or LinqExtendedBase return a Linq<T> or LinqExtended<T>, those methods would have to be overridden by more derived classes wanting to return themselves or subclasses of themselves. The question I asked in our discussion was whether you'd have an idea on how this could be avoided. 

Without overriding the where method explicitly I don't see this happening.  I might misunderstand your intent for your use-case.  But the `.where(predicate)` method _should always_ return the same type that it belongs to.  This is now exactly how the inheritance behaves.  It's simply a filter.

**Comment by electricessence** [comment]
I reviewed your changes.  I appreciate the work.  But changes going forward should work with the implemented base classes, etc.
Although I'm not enforcing every style nuance, this repo does use tabs for indent.
I do encourage you to take v1.2 as-is and attempt to make tweaks that might work in your favor and possibly attempt another PR.

**Comment by ThomasBarnekow** [comment]
> > Where methods implemented by LinqBase or LinqExtendedBase return a Linq or LinqExtended, those methods would have to be overridden by more derived classes wanting to return themselves or subclasses of themselves. The question I asked in our discussion was whether you'd have an idea on how this could be avoided.
> 
> Without overriding the where method explicitly I don't see this happening. I might misunderstand your intent for your use-case. But the `.where(predicate)` method _should always_ return the same type that it belongs to. This is now exactly how the inheritance behaves. It's simply a filter.

Sorry, you misunderstood my question. Replace "Where methods" with "If methods" in my first sentence. It has nothing to do with the `where(predicate: PredicateWithIndex<T>): TLinq` method. This is about the methods that are currently explicitly returning a `Linq<T>` or `LinqExtended<T>` rather than a generic type such as `TLinq`. For example:

- `select<TResult>(selector: SelectorWithIndex<T, TResult>): Linq<TResult>`
- `selectMany<TResult>(selector: SelectorWithIndex<T, Iterable<TResult>>): Linq<TResult>`

**Comment by electricessence** [comment]
AH!  Ok.  There's no way around that as you have to explicitly expose the `TResult`.  I wish there was, but there is not.
I added them as `Iterable<T>` to the base class because it did provide value for those common cases where the consumer would simply:
```ts
for(const e of linq(source)
    .where(predicate)
    .skip(10).take(10)
    .select(mapping)) {
    // Iterate filtered and mapped results.
}
```

Sadly, you have to override these `TResult` methods because you can't use the `TLinq` pattern to do that.

One thing I would love for TypeScript to allow was to override the typing in the sub-classes.   Like the `new` keyword in C#.
But as far as I know, that's not a thing. :(  So we have to override these in sub-classes.

**Comment by ThomasBarnekow** [comment]
> I reviewed your changes. I appreciate the work. But changes going forward should work with the implemented base classes, etc. Although I'm not enforcing every style nuance, this repo does use tabs for indent. I do encourage you to take v1.2 as-is and attempt to make tweaks that might work in your favor and possibly attempt another PR.

Regarding the style, could you provide a `.prettierrc` (or `.editorconfig`) that reflects your style? Without something like that, it is hard to comply.

Regarding your v1.2, I see those base classes as an optional convenience feature. The "real meat" lies in the functions that are exposed through those classes. Do you agree with that statement?

In their current shape, the base classes do not provide enough of what I need to justify a dependency and the associated risk of incurring breaking changes to my public API. Further, as suggested by this PR, I am not entirely happy with the shape of the API offered by those base classes. Therefore, I don't think that I am going to use them.

For example, the `single()`, `first()`, and `last()` methods and their corresponding `OrDefault()` siblings as provided by `LinqResolverBase` (not sure why you did not call that `LinqExtendedBase`) are incompatible with their .NET counterparts and, therefore, do not offer the API that I want to provide (i.e., something that is compatible with the .NET world). In .NET, those methods allow you to specify a predicate, which I **always** use unless I don't need a predicate. In fact, ReSharper always proposes to replace `.where(predicate).first()`, for example, with `.first(predicate)`. Thus, if I were to reimplement portions of my C# codebase in TypeScript, I would definitely need those methods.

While you would not see any occurrence of something like `.where(predicate).first()` in my codebase, you can of course still use that pattern even with my API ... unless you write C# code, have ReSharper, and accept the suggestions to streamline your code.

**Comment by ThomasBarnekow** [comment]
> AH! Ok. There's no way around that as you have to explicitly expose the `TResult`. I wish there was, but there is not.
> I added them as `Iterable<T>` to the base class because it did provide value for those common cases [...]

They don't have to return `Iterable<TResult>`. They can return `Linq<TResult>` or `LinqExtended<TResult>`, for example. However, that still means we'll have to override those methods in subclasses that want to return a more derived class.

**Comment by electricessence** [comment]
> Regarding the style, could you provide a .prettierrc (or .editorconfig) that reflects your style? Without something like that, it is hard to comply.

I originally had something like this but it was causing issues.  I'll look into it again.

**Comment by electricessence** [comment]
> In their current shape, the base classes do not provide enough of what I need to justify a dependency and the associated risk of incurring breaking changes to my public API. 

I'm a bit shocked and confused by this as the changes (for the most part) were made in order to accommodate the inheritance you needed.  I wouldn't worry about further breaking changes (as I commented in the other thread).

If you can't use them, then you can't use them, and I can totally understand that as inheritance can end up just being bloat.
They then become a template (or possible guide) for you or others to write their own LINQ helper classes.

The changes I made yesterday, I did not make lightly.  I saw them as necessary. 
https://github.com/OpenXmlDev/linq-to-xml/issues/1#issuecomment-1025156225

**Comment by electricessence** [comment]
> For example, the single(), first(), and last() methods and their corresponding OrDefault() siblings as provided by LinqResolverBase (not sure why you did not call that LinqExtendedBase) 

Because it extended from `LinqBase<T>` and ultimately provided _resolutions_ for other classes to inherit from.
In the end, the name matters little as it is exposed as `default` and any consumer can call it what they will.

I admit, I struggled with naming.  `LinqExtendedBase` didn't seem right to me as `LinqExtended` has a lot more purpose on it's own.

**Comment by electricessence** [comment]
| ... incompatible with their .NET counterparts and, therefore, do not offer the API that I want to provide (i.e., something that is compatible with the .NET world). In .NET, those methods allow you to specify a predicate, which I always use unless I don't need a predicate. In fact, ReSharper always proposes to replace .where(predicate).first(), for example, with .first(predicate). Thus, if I were to reimplement portions of my C# codebase in TypeScript, I would definitely need those methods.

I think you have a fair point here.
I propose that it is completely safe to add an optional delegate to `.first(predicate?)` `.last(predicate?)` and `.single(predicate?)`.
This does no harm, and extends value. The issue I have is that it does get confusing as it is inconsistent with the `orDefault` methods.

I'll think on it and await your comment.

**Comment by electricessence** [comment]
Keep in mind that `.defaultIfEmpty()` does not solve every case as `.single()` throws if there are more than one.  (As it does in .NET)

**Comment by ThomasBarnekow** [comment]
> > I changed the implementations of first(), last(), and single() and the corresponding xOrDefault() methods. Firstly, they should all take an optional predicate. Secondly, xOrDefault() should not take a default value if you want to mimic the .NET counterparts. Thus, my proposed implementations take a predicate but no default value. However, I added the defaultIfEmpty(defaultValue: T): TLinq method to deal with that.
> 
> I have a hard time agreeing with this one as I've previously spent a lot of time considering why it should or shouldn't be that way.
> 
> ```ts
> linqSequence
>   .where(predicate)
>   .firstOrDefault()
> // vs
> linqSequence
>   .firstOrDefault(predicate)
> ```
> 
> Here's the problem: You simply can't have the best of both worlds here. Exposing a default value option is important in TypeScript because there might be a preference of returning `null` instead of `undefined` or `0` instead of `undefined` if it's a number. Covering default value use cases would be a painful and probably bug ridden block of code. This is not an issue in C# as it has a real type system that will return 0 as a default value for a number and null for a string, etc. IMO, the former `.where(predicate).firstOrDefault()` is a more explicit, and simpler implementation.
> 
> As a side effect of this type of implementation, it can be difficult if not impossible to have a delegate as a parameter as it could be confused with an element in the collection.

Looking at your code snippet above, `linqSequence.firstOrDefault(predicate)` is more concise, not less explicit, and suggested by ReSharper in C# instead of `linqSequence.where(predicate).firstOrDefault()`. If you look at the code in this PR, you will see that I added the following method, which does the job of filtering the sequence:

```typescript
private filterSequence(predicate?: PredicateWithIndex<T>): Iterable<T> {
    return predicate ? where(predicate)(this.source) : this.source;
}
```

This is used by all methods offering an optional predicate. For example:

```typescript
firstOrDefault(predicate?: PredicateWithIndex<T>): T | null {
    return firstOrDefault<T>()(this.filterSequence(predicate)) ?? null;
}
```

Talking about default values, consider the following code snippet, which shows exactly what one would do in .NET:

```typescript
const result = linqSequence
    .defaultIfEmpty(defaultValue)
    .firstOrDefault()
```

What is the problem with that?

Yes, you can offer an overload in TypeScript that takes a default value. However, you should also offer an overload that corresponds to what you have in .NET.

Looking at your implementation of `firstOrDefault<T>(defaultValue: T): IterableTransform<T, T>`, it essentially reimplements what you have already implemented in your own implementation of `defaultIfEmpty<T>(defaultValue: T): IterableFilter<T>`. Why didn't you compose the two?

**Comment by electricessence** [comment]
> They don't have to return Iterable<TResult>. They can return Linq<TResult> or LinqExtended<TResult>, for example. However, that still means we'll have to override those methods in subclasses that want to return a more derived class.

This makes an argument that there is no value in `select` and `selectMany` in the base classes.
You might be right.

**Comment by electricessence** [comment]
In response to your above comment about firstOrDefault.  https://github.com/tsdotnet/linq/pull/3#issuecomment-1025193004

Explain to me how you would offer configuring a default value for `.singleOrDefault()` without things getting way more complicated than they are.   Remember that TS and C# are different.  0 is the default for a number in C# but not in TS.

**Comment by ThomasBarnekow** [comment]
> > In their current shape, the base classes do not provide enough of what I need to justify a dependency and the associated risk of incurring breaking changes to my public API.
> 
> I'm a bit shocked and confused by this as the changes (for the most part) were made in order to accommodate the inheritance you needed. I wouldn't worry about further breaking changes (as I commented in the other thread).

You would have to go "all in" and not introduce any conflicting or unwanted APIs for me to be able to extend those classes. You don't have to do that, of course. However, in that case, I am better off with my own root base class. No hard feelings here. Your base classes will add value for other users.

**Comment by electricessence** [comment]
> You would have to go "all in" and not introduce any conflicting or unwanted APIs for me to be able to extend those classes. You don't have to do that, of course. However, in that case, I am better off with my own root base class. No hard feelings here. Your base classes will add value for other users.

I would like to not touch the API at all.  I would like this repo to be complete and golden.
The changes I made were for the better because you showed me the benefit.
I would like to help make your work easier if I can and if it 'fits' it would prove to me that I don't need to make any more changes.

**Comment by electricessence** [comment]
Keeping an open mind (me).
Adding `.first`, `.single` and `.last` (and their respective `.orDefault()` methods is very new for LinqExtended.
They could be done different.

But you have to explain to me how you would solve the default problem as I mentioned above.
https://github.com/tsdotnet/linq/pull/3#issuecomment-1025193828

**Comment by ThomasBarnekow** [comment]
> In response to your above comment about firstOrDefault.
> 
> Explain to me how you would offer configuring a default value for `.singleOrDefault()` without things getting way more complicated than they are. Remember that TS and C# are different. 0 is the default for a number in C# but not in TS.

Firstly, to be honest, I almost never (> 99% of the cases) set a default value with `DefaultIfEmpty()` in C#. Therefore, I would likely not miss anything if there was no option to set a default value, be it with `defaultIfEmpty(defaultValue: T)` or by way of an optional parameter of `firstOrDefault()`, for example.

Secondly, I use those methods to make assertions about the sequences. For example, where I expect exactly one element, I use `Single()` and not `First()` or even `FirstOrDefault()`. Where I expect zero or one element, I use `SingleOrDefault()`, not `FirstOrDefault()`, for example. When `SingleOrDefault()` returns `null`, this is just a case that needs to be treated somehow.

For example, in Open XML, the `w:document` element can have zero or one `w:body` children. Assuming `document` represents the `w:document` `XElement`, if you try to get the body element by calling `document.elements(W.body).singleOrDefault()` and that returns `null`, you'd have to add a new `w:body` `XElement` to its parent `w:document` before you can continue. If the result is not `null`, you can work with it.

If I had to produce a default value for `singleOrDefault()`, I would do the following:

```ts
const value = linqSequence
    .defaultIfEmpty(defaultValue)
    .singleOrDefault();
```

This would return `defaultValue` in case `linqSequence` was empty. It would still throw if the sequence contained more than one element. That would be totally fine because, if I use `singleOrDefault()`, this is exactly what I want. Thus, my rules would be as follows:

- Don't use `single()` if you do not want to assert that the sequence contains exactly one element.
- Don't use `singleOrDefault()` if you do not want to assert that the sequence contains zero or one element.

**Comment by electricessence** [comment]
@ThomasBarnekow ... Here's a thought I just had.
In respect to the .orDefault methods...
Remember that in C# `default` is specific to that type.
But what about:
```ts
.firstOrUndefined() // no value param required or expected.
.firstOrUndefined(predicate)
```
It would then be possible to allow for

```ts
firstOrDefault<T>(T defaultValue,  predicate?: PredicateWithIndex<T>) : T
```

**Comment by electricessence** [comment]
I think you're missing the point here.
https://github.com/tsdotnet/linq/pull/3#issuecomment-1025199411

Without potentially adding a lot of code, `.firstOrDefault<number>()` (TS) will behave differently than `.FirstOrDefault<double>()` in C#.  (Because you'd have to cover all cases for all types)

Your point is well taken about `.DefaultIfEmpty()`.   I can't remember seeing it.

**Comment by electricessence** [comment]
BTW, I have no qualms adding this as an overload:
`firstOrDefault<T>(T defaultValue,  predicate?: PredicateWithIndex<T>) : T`

**Comment by ThomasBarnekow** [comment]
> > You would have to go "all in" and not introduce any conflicting or unwanted APIs for me to be able to extend those classes. You don't have to do that, of course. However, in that case, I am better off with my own root base class. No hard feelings here. Your base classes will add value for other users.
> 
> I would like to not touch the API at all. I would like this repo to be complete and golden. The changes I made were for the better because you showed me the benefit. I would like to help make your work easier if I can and if it 'fits' it would prove to me that I don't need to make any more changes.

I do accept that you would like to not touch the API at all. Mind you I also don't ask you to do that (the main purpose of this PR was to show you how to correctly implement the pattern, which you should still consider doing). But since you somehow wanted me to inherit from your base classes, I am just explaining to you what you would have to do for me to be able to do that (i.e., accept the PR in its essence). The changes you would have to make are more involved than what you would want to do -- which is completely fine. Therefore, I still need to establish my own root class, which is already done and fully covered by unit tests.

The beauty of your project is that it offers functions (filters, transformations, resolutions) that can be combined in any desired way. This is why I use it.

**Comment by ThomasBarnekow** [comment]
> I think you're missing the point here. [#3 (comment)](https://github.com/tsdotnet/linq/pull/3#issuecomment-1025199411)
> 
> Without potentially adding a lot of code, `.firstOrDefault<number>()` (TS) will behave differently than `.FirstOrDefault<double>()` in C#. (Because you'd have to cover all cases for all types)
> 
> Your point is well taken about `.DefaultIfEmpty()`. I can't remember seeing it.

It's taken a while, but now I think I got your point on the default values. My use cases almost always deal with reference types (e.g., `XElement`, `XAttribute`, `string`), where `null` is indeed the default value, so sequences of value types where the default value would be `0` or `false`, for example, are not "high on my list". If you wanted to treat them correctly all the time, wouldn't you have to require a default value parameter as in the overload below?

> `firstOrDefault<T>(T defaultValue, predicate?: PredicateWithIndex<T>) : T`

Would there even be an option to deal with that in code alone, i.e., without providing a default value? The value types that require special treatment would be `number`, `bigint`, and `boolean`, right? How do you determine the element type of an empty sequence?

Lastly, here are some links regarding `DefaultIfEmpty()`:

- [public static IEnumerable<TSource> DefaultIfEmpty<TSource>(this IEnumerable<TSource> source, TSource defaultValue)](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Linq/src/System/Linq/DefaultIfEmpty.cs) in .NET
- [defaultIfEmpty<T> (defaultValue: T): IterableFilter<T>](https://github.com/ThomasBarnekow/linq/blob/master/src/filters/defaultIfEmpty.ts) in your own repo

**Comment by electricessence** [comment]
@ThomasBarnekow Here is my proposed change.
https://github.com/tsdotnet/linq/pull/5/files#diff-fa0157cfacfede9e5e324cac6b8d5a2f2031fe7c9d9cd95b87db1404fd68d4cf
If you approve, I will merge and publish as v1.3

I think this makes things better overall with a more straight forward and explicit API.
As a dev, you won't be able to make the mistake of what you get back or not.
It solves your request to have these methods take predicates.

**Comment by electricessence** [comment]
The .d.ts looks like this now: (if approved)
```ts
/**
 * @author electricessence / https://github.com/electricessence/
 * @license MIT
 */
import { PredicateWithIndex } from '@tsdotnet/common-interfaces';
import LinqBase from "./LinqBase";
export default abstract class LinqExtendedBase<T, TLinq extends LinqExtendedBase<T, TLinq>> extends LinqBase<T, TLinq> {
    constructor(source: Iterable<T>, create: (source: Iterable<T>) => TLinq);
    /**
     * Returns all the entries in the sequence as a new array.
     * @return {T[]}
     */
    toArray(): T[];
    /**
     * Returns the number of entries in a sequence.
     * If a predicate is provided, filters the count based upon the predicate.
     * Otherwise counts all the entries in the sequence.
     * @param {PredicateWithIndex<T>} [predicate]
     * @return {boolean}
     */
    count(predicate?: PredicateWithIndex<T>): number;
    /**
     * Returns true if the predicate ever returns true; otherwise false.
     * If no predicate is provided, returns true if the sequence has any entries.
     * @param {PredicateWithIndex<T>} [predicate]
     * @return {boolean}
     */
    any(predicate?: PredicateWithIndex<T>): boolean;
    /**
     * Returns false if the predicate ever returns false; otherwise true.
     * @param {PredicateWithIndex<T>} [predicate]
     * @return {boolean}
     */
    all(predicate: PredicateWithIndex<T>): boolean;
    /**
     * Returns the expected single element; otherwise throws an InvalidOperationException.
     * @param {PredicateWithIndex<T>} [predicate]
     * @return {T}
     */
    single(predicate?: PredicateWithIndex<T>): T;
    /**
     * Returns the expected single element; otherwise the provided default value.
     * @param {T} defaultValue
     * @param {PredicateWithIndex<T>} [predicate]
     * @return {T}
     */
    singleOrDefault(defaultValue: T, predicate?: PredicateWithIndex<T>): T;
    /**
     * Returns the expected single element; otherwise undefined.
     * @param {PredicateWithIndex<T>} [predicate]
     * @return {T | undefined}
     */
    singleOrUndefined(predicate?: PredicateWithIndex<T>): T | undefined;
    /**
     * Returns the first element of the sequence.
     * @param {PredicateWithIndex<T>} [predicate]
     * @return {T}
     */
    first(predicate?: PredicateWithIndex<T>): T;
    /**
     * Returns the first element of the sequence or the default value if no element is found.
     * @param {T} defaultValue
     * @param {PredicateWithIndex<T>} [predicate]
     * @return {T}
     */
    firstOrDefault(defaultValue: T, predicate?: PredicateWithIndex<T>): T;
    /**
     * Returns the first element of the sequence; otherwise undefined.
     * @param {PredicateWithIndex<T>} [predicate]
     * @return {T | undefined}
     */
    firstOrUndefined(predicate?: PredicateWithIndex<T>): T | undefined;
    /**
     * Returns the last element of the sequence.
     * @param {PredicateWithIndex<T>} [predicate]
     * @return {T}
     */
    last(predicate?: PredicateWithIndex<T>): T;
    /**
     * Returns the last element of the sequence or the default value if no element is found.
     * @param {T} defaultValue
     * @param {PredicateWithIndex<T>} [predicate]
     * @return {T}
     */
    lastOrDefault(defaultValue: T, predicate?: PredicateWithIndex<T>): T;
    /**
     * Returns the last element of the sequence; otherwise undefined.
     * @param {PredicateWithIndex<T>} [predicate]
     * @return {T | undefined}
     */
    lastOrUndefined(predicate?: PredicateWithIndex<T>): T | undefined;
}

```

**Comment by electricessence** [comment]
Ok after refining and reviewing, I can't see this class going backwards.
I'm going to approve the PR and publish.

**Comment by electricessence** [comment]
You'll also note I renamed it to `LinqExtendedBase` as you suggested.

**Comment by ThomasBarnekow** [comment]
Here are my thoughts:

- Looking at some of the methods (e.g., `toArray()`) in conjunction with those that you added to `LinqBase`, how did you determine what should already be added to `LinqBase` vs. `LinqExtendedBase`? If you want to extend the API of `Linq<T>` already, wouldn't it make sense to also consider other very frequent or simple methods as well?
- Regarding the `OrUndefined()` methods, I would return `null` instead of `undefined` to signal the absence of a value. Therefore, if you wanted to add a method like that, I would call it `OrNull()` rather than `OrUndefined()`. However, I think I am even fine with the `OrDefault()` methods returning `null` in TypeScript / JavaScript. That is a language-specific "trait". For example, earlier today, I played with the following overloads:

```ts
firstOrDefault(): T | null;
firstOrDefault(predicate: PredicateWithIndex<T>): T | null;
firstOrDefault(defaultValue: T): T;
```

However, it looks like you have already made up your mind and merged your PR.

**Comment by electricessence** [comment]
So as I mentioned before, YOU CANNOT mix and match these methods in TS.

```ts
firstOrDefault(): T | null;
firstOrDefault(predicate: PredicateWithIndex<T>): T | null;
firstOrDefault(defaultValue: T): T;
```

The proposed above would have the side effect of not being able to differentiate between a collection of delegates as a default value or the default value itself...

Like so:
```ts
linq([x=>'a', x=>'b', x=>'c']).firstOrDefault(x=>'d') // What is supposed to happen here? 
```

**Comment by electricessence** [comment]
> Regarding the OrUndefined() methods, I would return null instead of undefined to signal the absence of a value.

Keep in mind that:
- `null == undefined` but `null !== undefined`.
- `null` in JavaScript is used quite often and tends to represent what is says: 'a null value'.  `null` is also (get ready) an _object_.  So `typeof(null) == 'object'` So there is a lot of screwy things that can happen with it.  https://stackoverflow.com/questions/18808226/why-is-typeof-null-object  things that can happen with `null`.
- `undefined` tends to mean what it means the value or key is 'missing'.  And that is exactly what you are asking of the API.  Is the value missing?

Here's another example to consider:
```ts
let m = { "a" : null, "b": undefined };
```
`a` will be `null`, `b` will be `undefined`, `c` is also `undefined`.  But is there still a key in the map for `b`?  What is the length of `Object.keys(m)`?  As you might expect, it _is_ 2.  But this can get confusing as well.  But it's generally rare for someone to have a key as `undefined` for this exact reason, and placeholders will typically be `null`.

**Comment by ThomasBarnekow** [comment]
> So as I mentioned before, YOU CANNOT mix and match these methods in TS.
> 
> ```ts
> firstOrDefault(): T | null;
> firstOrDefault(predicate: PredicateWithIndex<T>): T | null;
> firstOrDefault(defaultValue: T): T;
> ```
> 
> The proposed above would have the side effect of not being able to differentiate between a collection of delegates as a default value or the default value itself...
> 
> Like so:
> 
> ```ts
> linq([x=>'a', x=>'b', x=>'c']).firstOrDefault(x=>'d') // What is supposed to happen here? 
> ```

Consider the following type definition:

```ts
export interface SelectorWithIndex<TSource, TResult>
{
    (source: TSource, index: number): TResult;
}

export type PredicateWithIndex<T> = SelectorWithIndex<T, boolean>;
```

The expression `x=>'d'` is not a `PredicateWithIndex<T>` because `'d'` is not a `boolean`. Therefore, the TypeScript compiler will complain. However, it is possible to construct a case where the default value and the predicate would not be distinguishable. However, that would be a pretty artificial edge case.

```ts
const sequence = linqIterable<(source: any) => boolean>([
  () => true,
  () => false,
  () => true,
]).firstOrDefault(() => true);
```

In the above case, the parameter would be deemed a predicate. You'd have to a combination of `where()`, `defaultIfEmpty()` and a parameterless `firstOrDefault()`.

**Comment by ThomasBarnekow** [comment]
Thinking about the default value again, there might be better ways for specifying value as opposed to using a parameter of the `OrDefault()` functions. For example, it might be a parameter passed to:

- the constructors of `Linq<T>` or `LinqExended<T>` classes,
- the `linq()` or `linqExtended()` methods,
- `defaultIfEmpty()` transformation, which might ultimately be used by the above mechanisms.

The reason for having to specify a non-`undefined` or non-`null` default value for iterables of `number`, `bigint`, or `boolean` is related to the language. It is easy to return either `undefined` or `null`. To return `0` for `number` or `bigint` or `false` for `boolean`, you could specify that either when creating a sequence (using the constructor or factory functions) or using `defaultIfEmpty()`.

What do you think? In my API, I will not add default value parameters to the `OrDefault()` methods.

**Comment by electricessence** [comment]
https://github.com/tsdotnet/linq/pull/3#issuecomment-1025235691
I say again.  You'll have to trust me on this one.  Mixing these overloads in TS/JS is a disaster waiting to happen.

That said, the current changes avoid that problem completely and facilitate all possible behaviors.

**Comment by electricessence** [comment]
https://github.com/tsdotnet/linq/pull/3#issuecomment-1025239845
This is exactly what I'm trying to avoid which is a more convoluted solution to the problem.
Things will start to permute in ways that create complexity.

Consider that if you added a property called `.defaultValue` to `LinqExtendedBase<T>` or even a fluent API method like `.setDefault(value:T)`.  What if it wasn't set? Then unexpected behavior?  You would probably have to have an entirely new `LinqExtendedWithDefault<T>` class (for typing purposes) that allows you to overload `.firstOrDefault()` that adds type safety.

I think your best bet is the following options:

1. `.firstOrDefault(null, x=>...)`
2. We could add `.firstOrNull(x=>...)`. 

No.2 I would be willing to do, but I don't find it necessary as `null==undefined`.

**Comment by electricessence** [comment]
BTW if you like ReSharper, I suggest you try WebStorm to code your TS. 😉

**Pull request closed without merging**
